
version: "3.6"
services:
  postgresql:
    image: postgres:12.16
    container_name: server_bd
    restart: always
    shm_size: 1g
    environment:
      - POSTGRES_DB=server
      - POSTGRES_USER=server
      - POSTGRES_PASSWORD=198416
      - POSTGRES_ROOT_PASSWORD=198416
    ports:
      - "6667:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      svacer:
networks:
  svacer:
